{% set name = "pyspnego" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyspnego-{{ version }}.tar.gz
  sha256: 58d352d901baab754f63cb0da790c1f798605eb634f7f922df9bb6822d3de3c5

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python  >=3.7
    - cryptography
    - cython
    - pip
  run:
    - python  >=3.7
    - cryptography
    - ruamel.yaml
  run_constrained:
    - python-gssapi >=1.5.0  # [not win]
    - krb5 >=0.3.0  # [not win]

test:
  imports:
    - spnego
    - spnego._ntlm_raw
    - spnego._sspi_raw  # [win]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jborean93/pyspnego
  summary: Windows Negotiate Authentication Client and Server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - krisevans
    - rzillman
